In [14]:
import numpy as np

In [15]:
np.__version__

'1.19.2'

In [16]:
linspace(10)

NameError: name 'linspace' is not defined

In [ ]:
a=np.array[(1,2,3,4,5)]

In [20]:
a

array([1, 2, 3, 4, 5])

In [ ]:
a=np. array[(1,2,3,4,5)]

In [ ]:
a = np.array[(1,2,3,4,5)]

In [ ]:
a = np.array[(1 ,2 ,3 ,4 ,5 )]

In [17]:
a = np.array([1, 2, 3, 4, 5])

In [22]:
b = np.array([6, 7, 8])

In [23]:
b

array([6, 7, 8])

In [24]:
type(a),type(b)

(numpy.ndarray, numpy.ndarray)

In [26]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [29]:
np.linspace(0, 20, num=21, endpoint=True, retstep=False, dtype=None, axis=0)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20.])

In [30]:
np.linspace(0,20,num=11, endpoint=True, retstep=False, dtype=None, axis=0)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [31]:
np.linspace(0,20,num=7,endpoint=True,retstep=False, dtype=None, axis=0)

array([ 0.        ,  3.33333333,  6.66666667, 10.        , 13.33333333,
       16.66666667, 20.        ])

In [32]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [34]:
np.arange(21)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [35]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [36]:
np.arange(3,21,3)

array([ 3,  6,  9, 12, 15, 18])